# Generated by Django 3.2.5 on 2021-09-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_logger_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=380906006060, max_length=12),
            preserve_default=False,
        ),
    ]
