# Generated by Django 3.2.5 on 2021-09-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20210922_1134'),
        ('students', '0007_remove_student_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(db_column='group id', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(db_column='age', default=18),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='first name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_column='phone', max_length=13),
        ),
    ]
