version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: dockerfile
    image: andrson451/django_trushevych
    command: runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - db
    volumes:
      - ./:/app

  celery-worker:
    build:
      context: .
      dockerfile: dockerfile-celery
    command: -A django_trushevych worker -l info
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/home/user

  celery-beat:
    build:
      context: .
      dockerfile: dockerfile-celery
    command: -A django_trushevych beat -l info
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
