version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: andrson451/django_trushevych
    command: runserver 0.0.0.0:3000
    ports:
      - 3000:3000
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672


  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: -A django_trushevych worker -l info
    depends_on:
      - db
      - rabbitmq

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: -A django_trushevych beat -l info
    depends_on:
      - db
      - rabbitmq