# Generated by Django 3.2.5 on 2021-09-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_exchange_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='buy_price',
            field=models.DecimalField(db_column='buy price', decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='creation date'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Ruble')], db_column='currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sell_price',
            field=models.DecimalField(db_column='sell price', decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='source',
            field=models.CharField(db_column='Source', max_length=100),
        ),
    ]
