# Generated by Django 3.2.5 on 2021-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20210922_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('840', 'US Dollar'), ('978', 'Euro')], db_column='currency', max_length=10),
        ),
    ]
