# Generated by Django 3.2.5 on 2021-09-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone'),
        ('teachers', '0006_rename_teachers_teacher'),
        ('group', '0003_auto_20210921_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
