# Generated by Django 3.2.5 on 2021-09-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone'),
        ('group', '0004_auto_20210922_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='main_student',
            field=models.OneToOneField(db_column='Group monitor ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
